package com.assemblypayments.ramenpos.logic.enums

enum class AppEvent {
    CONNNECTION_STATUS_CHANGED,
    PAIRING_FLOW_CHANGED,
    TRANSACTION_FLOW_STATE_CHANGED,
    SECRET_DROPPED,
    PRINTING_RESPONSE,
    TERMINAL_STATUS_RESPONSE,
    TERMINAL_CONFIGURATION_RESPONSE,
    BATTERY_LEVEL_CHANGED,
    DEVICE_ADDRESS_CHANGED
}